version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: my_database

  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: my_database
    command: sh -c "yarn install --production && node src/index.js"
  
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home

volumes:
  jenkins:




